
name: CI

on:
  workflow_dispatch:
    inputs:
      selection:
        type: choice
        required: true
        description: Select tenant group
        options:
          - All
          - Custom
      group:
        type: text
        description: "Specify tenant. Example: fuw, tagesanzeiger, baz"


jobs:
  fuw:
    if: ${{ contains(inputs.selection, 'All') || (contains(inputs.selection, 'Custom') && contains(inputs.group, 'fuw')) }} 
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, FuW!
  
  tagesanzeiger:
    if: ${{ contains(inputs.selection, 'All') || (contains(inputs.selection, 'Custom') && contains(inputs.group, 'tagesanzeiger')) }} 
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, Tagi!
  
  baz:
    if: ${{ contains(inputs.selection, 'All') || (contains(inputs.selection, 'Custom') && contains(inputs.group, 'baz')) }} 
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, BaZ!
